language: python

python:
  - "2.7"
  - "3.8"

sudo: true

services:
  - docker

before_install:
  - sudo bash ./travis/run_es_docker.sh

install:
  - pip install tox-travis
  - pip install codecov

before_script:
  - sleep 10

script: tox

after_success:
  - codecov

notifications:
  email: false
